CREATE TABLE EMP_TMEP2 AS SELECT * FROM EMP;

SELECT * FROM EMP_TMEP2;

-- JOBDL MANAGER인 데이터 삭제하기

DELETE FROM emp_tmep2 WHERE JOB='MANAGER';

ROLLBACK;

DELETE EMP_TMEP2; -- 전부 삭제

-- EMP_TMEP2 테이블의 사원 중에서 급여가 5000이상인 사원 삭제
DELETE FROM emp_tmep2 WHERE sal >= 5000;

-- ppt 실습

-- EMP 테이블의 내용을 이용하여 EXAM_EMP 생성
CREATE TABLE EXAM_EMP AS SELECT * FROM EMP;
-- DEPT 테이블의 내용을 이용하여 EXAM_DEPT 생성
CREATE TABLE EXAM_DEPT AS SELECT * FROM DEPT;
-- SALGRADE 테이블의 내용을 이용하여 EXAM_SALGRADE 생성
CREATE TABLE EXAM_SALGRADE AS SELECT * FROM SALGRADE;

SELECT * FROM exam_emp;

-- 다음 정보를 EXAM_EMP 테이블에 입력하시오
INSERT INTO EXAM_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7201,'TEST_USER1','MANAGER',7788,'2016-01-02',4500,'',50);
INSERT INTO EXAM_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7202,'TEST_USER2','CLERK',7201,'2016-02-21',1800,'',50);
INSERT INTO EXAM_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7203,'TEST_USER3','ANALYST',7201,'2016-04-11',3400,'',60);
INSERT INTO EXAM_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7204,'TEST_USER4','SALESMAN',7201,'2016-05-31',2700,300,60);
INSERT INTO EXAM_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7205,'TEST_USER5','CLERK',7201,'2016-07-20',2600,'',70);
INSERT INTO EXAM_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7206,'TEST_USER6','CLERK',7201,'2016-09-08',2600,'',70);
INSERT INTO EXAM_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7207,'TEST_USER7','LECTURER',7201,'2016-10-28',2300,'',80);
INSERT INTO EXAM_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7208,'TEST_USER8','STUDENT',7201,'2018-03-09',1200,'',80);

-- EXAM_EMP에 속한 사원 중 50번 부서에서 근무하는 사원들의 평균 급여보다
-- 많은 급여를 받고 있는 사원들을 70번 부서로 옮기기
UPDATE EXAM_EMP
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL) FROM exam_emp WHERE DEPTNO=50);
-- EXAM_EMP에 속한 사원 중 60번 부서에서 입사일이 가장 빠른 사원보다 늦게 입사한 사원의 급여를
-- 10% 인상하고 80번 부서로 옮기기
UPDATE EXAM_EMP
SET DEPTNO = 80, SAL=SAL*1.1
WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM exam_emp WHERE DEPTNO=60);

-- EXAM_EMP에 속한 사원 중 급여 등급이 5인 사원을 삭제하기
DELETE FROM exam_emp WHERE EMPNO IN (SELECT EMPNO  
                                    FROM EMP_TMEP2 , SALGRADE   
                                    WHERE SAL BETWEEN LOSAL AND HISAL AND GRADE =5);

-- 급여 등급이 3등급 사이에 있는 30번 부서의 사원들만 제거
DELETE FROM EMP_TMEP2 WHERE EMPNO IN (SELECT E.EMPNO 
                                   FROM EMP_TMEP2 E, SALGRADE S 
                                   WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL 
                                   AND S.GRADE=3 AND DEPTNO=30);








